---

- name: "[WORDPRESS] - update cache"
  apt:
    update_cache: yes
  become: yes


- name: "[WORDPRESS] - install LAMP"
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items: "{{ package_name }}"

- name: "[WORDPRESS] - start apache2 mysql"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes
  with_items:
    - apache2
    - mysqld

